<?php

namespace App\Models;

use App\Models\Traits\Transform;
use App\Scopes\AdminScope;
use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable implements MustVerifyEmail
{
    use Notifiable;
    use Transform;

    public static $columns = [
        'name'              => '名称',
        'email'             => '邮箱',
        'email_verified_at' => '验证于',
        'created_format'    => '创建于',
    ];

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'is_admin', 'avatar'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    protected $appends = [
        'created_format'
    ];

    /**
     * 模型启动
     *
     * creator fjy
     */
    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        // 加载全局作用域
        static::addGlobalScope(new AdminScope());
    }

    public function articles()
    {
        return $this->hasMany(Article::class);
    }

    public function roles()
    {
        return $this->belongsToMany(Role::class)->withTimestamps();
    }

    /**
     * Get all permissions of user.
     *
     * @return mixed
     */
    public function allPermissions()
    {
        return $this->roles()->with('permissions')->get()->pluck('permissions')->flatten();
    }

    /**
     * author SimonTuo
     * @param $id
     * @return bool
     */
    public function isOwn($id): bool
    {
        if (user()->id != $id) {
            return false;
        }

        return true;
    }
}
